import os
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from datetime import datetime

SCOPES = [
    "https://www.googleapis.com/auth/youtube.upload",
    'https://www.googleapis.com/auth/drive.file'
]

FOLDER_ID = "15UdzxGEhy90E429SIBMQRwQz2LxlQU6U"  # Укажите ID папки AutoGeneratedVideos

def authenticate_google_drive():
    """Авторизация и получение клиента Google Drive API."""
    creds = None
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        with open('token.json', 'w') as token:
            token.write(creds.to_json())
    return build('drive', 'v3', credentials=creds)

def upload_to_google_drive(file_path, file_name):
    """Загружает видео в папку AutoGeneratedVideos на Google Диск."""
    drive_service = authenticate_google_drive()
    
    # Получаем текущую дату и форматируем её в строку
    current_date = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    file_name_with_date = f"{current_date}.mp4"
    
    file_metadata = {
        'name': file_name_with_date,  # Используем дату в названии файла
        'parents': [FOLDER_ID]  # Загружаем в указанную папку
    }
    
    media = MediaFileUpload(file_path, mimetype='video/mp4')
    file = drive_service.files().create(body=file_metadata, media_body=media, fields='id').execute()
    
    return file.get('id')

# Пример загрузки
if __name__ == "__main__":
    video_id = upload_to_google_drive("video.mp4", "example_video.mp4")
    print("Загруженный файл ID:", video_id)